"""operational schema

Revision ID: 0001
Revises:
Create Date: 2026-08-14 13:07:48.635868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reliability', sa.Enum('reliable', 'inconsistent', name='supplier_reliability'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_reliability', 'suppliers', ['reliability'], unique=False)
    op.create_table('inventory',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_inventory_quantity_on_hand_non_negative'),
    sa.CheckConstraint('safety_stock >= 0', name='ck_inventory_safety_stock_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location', name='uq_inventory_product_location')
    )
    op.create_index('ix_inventory_product_id', 'inventory', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('on_time', 'delayed', 'at_risk', 'delivered', name='order_status'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_orders_quantity_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_product_id', 'orders', ['product_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_supplier_id', 'orders', ['supplier_id'], unique=False)
    op.create_index('ix_orders_supplier_status', 'orders', ['supplier_id', 'status'], unique=False)
    op.create_table('deliveries',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('on_time', 'delayed', 'at_risk', 'delivered', name='order_status'), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_order_id', 'deliveries', ['order_id'], unique=False)
    op.create_index('ix_deliveries_order_status', 'deliveries', ['order_id', 'status'], unique=False)
    op.create_index('ix_deliveries_status', 'deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deliveries_status', table_name='deliveries')
    op.drop_index('ix_deliveries_order_status', table_name='deliveries')
    op.drop_index('ix_deliveries_order_id', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index('ix_orders_supplier_status', table_name='orders')
    op.drop_index('ix_orders_supplier_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_product_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_inventory_product_id', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('ix_suppliers_reliability', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('products')
    # ### end Alembic commands ###
    # autogenerate does not drop shared/native PG enum types on table drop; do it explicitly
    sa.Enum(name='order_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='supplier_reliability').drop(op.get_bind(), checkfirst=True)
